version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: ./docker/mongodb/Dockerfile
    image: shark-info:mongodb
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sharkdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - shark-network

 nodejs:
  build:
    context: .
    dockerfile: ./docker/nodejs/Dockerfile
  image: shark-info:nodejs
  container_name: nodejs-container
  ports:
    - "3000:3000"
  depends_on:
    - mongodb
  environment:
    MONGODB_URI: mongodb://mongodb:27017/sharkdb
  volumes:
    - ./nodejs-app:/app
    - /app/node_modules        
  networks:
    - shark-network

volumes:
  mongodb_data:
